# Project-wide Gradle settings.

# Increase memory for Gradle and Kotlin dexing (fix CI dex errors)
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8

# Disable daemon in CI
org.gradle.daemon=false

# Enable parallel build
org.gradle.parallel=true

# Disable caching to avoid corrupted CI caches
org.gradle.caching=false

# AndroidX configuration
android.useAndroidX=true
android.enableJetifier=true

# Disable R8 (avoid kotlin dex CI crash)
android.enableR8=false

# Kotlin configuration
kotlin.code.style=official
kotlin.incremental=false
kotlin.daemon.jvm.options=-Xmx2048m
